plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
    id("org.jetbrains.kotlin.plugin.serialization")
    id("com.google.devtools.ksp")
}

import java.io.FileInputStream
import java.util.Properties

// Read signing info from local.properties (generated by build_and_sign.sh, never committed)
val localProps = Properties().apply {
    val f = rootProject.file("local.properties")
    if (f.exists()) load(FileInputStream(f))
}
val hasSigning = localProps.getProperty("storeFile") != null

android {
    namespace = "com.huochang.yard"
    compileSdk = 34

    defaultConfig {
        applicationId = "com.huochang.yard"
        minSdk = 26
        targetSdk = 34
        versionCode = 1
        versionName = "1.0"

        vectorDrawables {
            useSupportLibrary = true
        }
    }

    signingConfigs {
        create("release") {
            if (hasSigning) {
                storeFile = file(localProps.getProperty("storeFile")!!)
                storePassword = localProps.getProperty("storePassword")
                keyAlias = localProps.getProperty("keyAlias")
                keyPassword = localProps.getProperty("keyPassword")
            }
        }
    }

    buildTypes {
        debug {
            isDebuggable = true
            isMinifyEnabled = false
        }
        release {
            isDebuggable = false
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
            if (hasSigning) {
                signingConfig = signingConfigs.getByName("release")
            }
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    buildFeatures {
        compose = true
        buildConfig = true
    }

    composeOptions {
        kotlinCompilerExtensionVersion = "1.5.14"
    }

    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }
}

dependencies {
    // 升级到 Compose 1.7.0 library line（仍配 Compose Compiler 1.5.14 + Kotlin 1.9.24，官方支持）。
    // 此前的 1.6.7 线在构建环境实际解析到的 foundation 手势包残缺
    // （gestures 包能找到但 pointerInput 等顶层符号缺失，background/clickable 在主包正常），
    // 升级到 1.7.0 线以绕开可能损坏/不完整的 1.6.7 artifact；版本仍显式钉死，避免传递降级。
    implementation("androidx.compose.ui:ui:1.7.0")
    implementation("androidx.compose.ui:ui-graphics:1.7.0")
    implementation("androidx.compose.ui:ui-tooling-preview:1.7.0")
    implementation("androidx.compose.material3:material3:1.3.0")
    implementation("androidx.compose.material:material-icons-extended:1.7.0")
    // Explicit foundation dependency: provides androidx.compose.foundation.gestures.*
    // (pointerInput, detectTapGestures, awaitPointerEventScope, awaitPointerEvent, ...).
    implementation("androidx.compose.foundation:foundation:1.7.0")
    implementation("androidx.activity:activity-compose:1.8.2")
    implementation("androidx.lifecycle:lifecycle-viewmodel-compose:2.7.0")
    implementation("androidx.lifecycle:lifecycle-runtime-compose:2.7.0")
    implementation("androidx.navigation:navigation-compose:2.7.7")

    // Room (offline-first local storage, replaces PWA localStorage)
    implementation("androidx.room:room-runtime:2.6.1")
    implementation("androidx.room:room-ktx:2.6.1")
    ksp("androidx.room:room-compiler:2.6.1")

    // kotlinx.serialization for JSON backup import/export
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.6.2")

    // Coroutines
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3")

    // Core utilities
    implementation("androidx.core:core-ktx:1.12.0")

    // FileProvider (for CSV/JSON export sharing) is part of androidx.core

    debugImplementation("androidx.compose.ui:ui-tooling:1.6.7")
}
