plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
    id("org.jetbrains.kotlin.plugin.serialization")
    id("com.google.devtools.ksp")
}

import java.io.FileInputStream
import java.util.Properties

// Read signing info from local.properties (generated by build_and_sign.sh, never committed)
val localProps = Properties().apply {
    val f = rootProject.file("local.properties")
    if (f.exists()) load(FileInputStream(f))
}
val hasSigning = localProps.getProperty("storeFile") != null

android {
    namespace = "com.huochang.yard"
    compileSdk = 34

    defaultConfig {
        applicationId = "com.huochang.yard"
        minSdk = 26
        targetSdk = 34
        versionCode = 1
        versionName = "1.0"

        vectorDrawables {
            useSupportLibrary = true
        }
    }

    signingConfigs {
        create("release") {
            if (hasSigning) {
                storeFile = file(localProps.getProperty("storeFile")!!)
                storePassword = localProps.getProperty("storePassword")
                keyAlias = localProps.getProperty("keyAlias")
                keyPassword = localProps.getProperty("keyPassword")
            }
        }
    }

    buildTypes {
        debug {
            isDebuggable = true
            isMinifyEnabled = false
        }
        release {
            isDebuggable = false
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
            if (hasSigning) {
                signingConfig = signingConfigs.getByName("release")
            }
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    buildFeatures {
        compose = true
        buildConfig = true
    }

    composeOptions {
        kotlinCompilerExtensionVersion = "1.5.14"
    }

    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }
}

dependencies {
    // Compose BOM manages all Compose library versions.
    // 2024.09.00 = Compose 1.6.7 — the library line whose androidx.compose.foundation.gestures.*
    //  symbols (pointerInput / awaitPointerEventScope / awaitPointerEvent / tryAwaitRelease) resolve
    //  cleanly under Compose Compiler 1.5.14 + Kotlin 1.9.24 (this exact pairing is verified by
    //  real-world projects). The previous 2024.02.00 (Compose 1.6.0) is NOT a match for Compiler 1.5.14
    //  (1.6.0 pairs with Compiler 1.5.13) and left those gesture symbols unresolvable.
    implementation(platform("androidx.compose:compose-bom:2024.09.00"))
    // Pin the core Compose artifacts to the EXACT BOM (2024.09.00 = 1.6.7) version. The BOM alone
    // let a transitive dependency silently hold androidx.compose.foundation on an older 1.6.0-era
    // build, which left the foundation.gestures.* symbols (pointerInput / detectTapGestures /
    // awaitPointerEventScope / awaitPointerEvent / tryAwaitRelease) unresolvable under Compose
    // Compiler 1.5.14. Pinning guarantees foundation 1.6.7, matching Compiler 1.5.14 + Kotlin 1.9.24.
    implementation("androidx.compose.ui:ui:1.6.7")
    implementation("androidx.compose.ui:ui-graphics:1.6.7")
    implementation("androidx.compose.ui:ui-tooling-preview:1.6.7")
    implementation("androidx.compose.material3:material3")
    implementation("androidx.compose.material:material-icons-extended")
    // Explicit foundation dependency: provides androidx.compose.foundation.gestures.*
    // (pointerInput, detectTapGestures, awaitPointerEventScope, tryAwaitRelease, ...).
    // Pinned to 1.6.7 to match the BOM / Compiler 1.5.14 (a transitive dep had been
    // silently downgrading this to the 1.6.0-era build, breaking gesture resolution).
    implementation("androidx.compose.foundation:foundation:1.6.7")
    implementation("androidx.activity:activity-compose:1.8.2")
    implementation("androidx.lifecycle:lifecycle-viewmodel-compose:2.7.0")
    implementation("androidx.lifecycle:lifecycle-runtime-compose:2.7.0")
    implementation("androidx.navigation:navigation-compose:2.7.7")

    // Room (offline-first local storage, replaces PWA localStorage)
    implementation("androidx.room:room-runtime:2.6.1")
    implementation("androidx.room:room-ktx:2.6.1")
    ksp("androidx.room:room-compiler:2.6.1")

    // kotlinx.serialization for JSON backup import/export
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.6.2")

    // Coroutines
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3")

    // Core utilities
    implementation("androidx.core:core-ktx:1.12.0")

    // FileProvider (for CSV/JSON export sharing) is part of androidx.core

    debugImplementation("androidx.compose.ui:ui-tooling")
}
